server:
  port: 8086

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 10MB
      # 整个请求最大大小
      max-request-size: 100MB
  cloud:
    openfeign:
      client:
        config:
          xiaohashu-user-relation:
            connectTimeout: 3000 # 连接超时（毫秒）
            readTimeout: 3000 # 读超时（毫秒）

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

