#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
#=================================================================
# 对象存储配置
#=================================================================
storage:
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: YOUR_MINIO_ACCESS_KEY_HERE
    secretKey: YOUR_MINIO_SECRET_KEY_HERE
  aliyun-oss:
    # OSS 服务的访问域名，请根据实际使用的 OSS 区域替换为对应的 endpoint
    endpoint: oss-cn-hangzhou.aliyuncs.com # 改成你自己的
    # 阿里云账号的 AccessKey ID，用于身份验证
    accessKey: YOUR_ALIYUN_ACCESS_KEY_HERE # 改成你自己的
    # 阿里云账号的 AccessKey Secret，用于身份验证
    secretKey: YOUR_ALIYUN_SECRET_KEY_HERE # 改成你自己的

